# docker-compose.yml

version: "3.7"
services:
  nestjs-app:
    build:
      context: .
    environment:
      DB_USER: ${USER}
      DB_PASSWORD: ${PASSWORD}
      DB_HOST: ${HOST}
    ports:
      - '3000:3000'
    env_file:
      - ./.env